Revert "Revert "Revert "8250: add support for ASIX devices with a FIFO bug"""
It's not worth reverting the entire commit just to fix the KMI.

Let's fix it another way while resolving the conflict with v5.10.235-rc1.

../drivers/tty/serial/8250/8250_pci.c:1879:9: error: 'PCI_VENDOR_ID_ASIX' macro redefined [-Werror,-Wmacro-redefined]
 1879 | #define PCI_VENDOR_ID_ASIX              0x9710
      |         ^
../include/linux/pci_ids.h:1768:9: note: previous definition is here
 1768 | #define PCI_VENDOR_ID_ASIX              0x125b
      |         ^

This reverts commit 986fd89af0659a1295fde5aecbb4e2784cc00a43.